### ISSUE TITLE
How to implement iOS push notifications?

### ISSUE THREAD

**Issue by fakerybakery** [TootSDK/TootSDK#204]
Hi,
Is there some guide to implement iOS push notifications?
Thanks

**Comment by davidgarywood** [comment]
Hi, this is currently beyond the scope of the SDK.

You’d do well to look at the source code for Feditext (formerly Metatext), and perhaps IceCubes as well as these are open source iOS apps for Mastodon that have notifications working.

My understanding of their process is that there is a web service you need to run yourself. The app then connects to that with its authorisation token etc so that the webservice receives web pushes from your instance, and then it forwards them to Apple’s service so your user can receive the push on device.

this isn’t something I’ve implemented myself though!

**Comment by fakerybakery** [comment]
OK, thanks for the clarification!

**Comment by kkostov** [comment]
@fakerybakery Like @davidgarywood said, the actual server push is something you will need to implement separately as it requires a server component.

Once you have the server bits setup, `TootSDK` has several methods to facilitate creating and managing the subscription (note that this part of the flow depends on your server setup).

[You can check](https://github.com/TootSDK/TootSDK/blob/main/Sources/TootSDK/TootClient/TootClient%2BNotifications.swift#L59) for example `createPushSubscription` which takes an instance of [`PushSubscriptionParams`](https://github.com/TootSDK/TootSDK/blob/main/Sources/TootSDK/Models/PushSubscriptionParams.swift) the encryption key needed by your back-end and information about which notifications the app should receive.

So to subscribe, you will end up doing something like this:

```swift
let subscr = PushSubscriptionParams.Subscription.init(
        endpoint: pushURI.absoluteString,
        keys: PushSubscriptionParams.Keys.init(p256dh: pushSubscription.p256dh, auth: pushSubscription.authData))
let params = PushSubscriptionParams(subscription: subscr, data: .init(alerts: Alerts(follow: true, favourite: true, repost: true, mention: true)))
```

**Comment by fakerybakery** [comment]
Hi, thanks for the clarification. Do you have any recommendations on what language would be best to implement the backend in? I looked a while back and found it was relatively hard to do in PHP.
