### ISSUE TITLE
Best practices on Mastodon log out

### ISSUE THREAD

**Issue by vincentneo** [TootSDK/TootSDK#264]
I realise that TootSDK doesn't implement Mastodon's `/oauth/revoke`. Upon searching, there seems to be an issue in the past (#174), that was converted to a discussion but is lost to history. (#175)

May I ask on what was discussed in #175, and if it's fine to not revoke/best practices on logout? Thanks!

**Comment by kkostov** [comment]
Hi @vincentneo , thank you for raising this issue. It seems GitHub doesn't have a way to recover the discussion. However, it's reasonable to expect that the SDK would provide this so I'm adding the method. You can expect it in a couple of minutes when the new version becomes available. 

Please note that in order to revoke an oauth token, you will need to retrain the clientId and clientSecret which the app had obtained during the first authentication.

Example logging out: https://github.com/TootSDK/TootSDK/blob/77688f4fc20293e80c1cb2608ecc38aa8f51d609/Examples/swiftyadmin/Sources/swiftyadmin/Logout.swift

Example reading the client id and secret immediately after a login: https://github.com/TootSDK/TootSDK/blob/77688f4fc20293e80c1cb2608ecc38aa8f51d609/Examples/swiftyadmin/Sources/swiftyadmin/Login.swift#L33C37-L33C59

**Comment by vincentneo** [comment]
Thank you!
