### ISSUE TITLE
GoToSocial support

### ISSUE THREAD

**Issue by Tunous** [TootSDK/TootSDK#287]
I would like to add support for GoToSocial but unfortunately I encountered issue with how TootSDK detects flavors. Right now it's based on `/api/v1/instance` endpoint and version property. This works for other flavors but GoToSocial doesn't include its name here like other services.

For example https://gts.superseriousbusiness.org/api/v1/instance returns `0.16.0+git-f1cbf6f`

I searched for alternatives and found that there is a `/nodeinfo/2.0` endpoint with software.name property. This works for GoToSocial and Mastodon

https://gts.superseriousbusiness.org/nodeinfo/2.0
https://mastodon.world/nodeinfo/2.0

Now my question is how to resolve this properly in TootSDK. Should connection method be extended to call this endpoint after calling instance endpoint? This would always require 2 calls for Mastodon. Or should detection based on instance endpoint be fully replaced with nodeinfo check?

I would prefer the second option but am not sure whether this endpoint is a standard among all flavors.

**Comment by kkostov** [comment]
@Tunous Good idea! The `connect` method only needs to set the flavour, so we can try to be smart about it.

I would add a new TootClient method which returns `NodeInfo` (for now, we only need to type the `software` block). `connect()` can then be modified to first try to get nodeInfo (which may fail or explode if it doesn't exist), in order to set the flavour. If nodeInfo fails, it can try to get the instanceInfo like it does today.

**Comment by technicat** [comment]
I filed an issue with gotosocial to add some identifying info to their instance in the same format as most other masto-compatible platforms, but they said to go with nodeinfo

https://github.com/superseriousbusiness/gotosocial/issues/2874

So I've been using this to check nodeinfo first

https://github.com/technicat/DiasporaNodeInfo

and as a fallback I check for "git" in the instance version string since gotosocial is the only one I know that has that. One glitch is that g2s has an admin switch that lets intances advertise as Mastodon, another is that without switch the nodeinfo and instance don't advertise the Mastodon version compatibility (I do version checks to determine feature availability), and I've seen some instances with unreadable (malformed JSON) nodeinfos.

I'm doing all my platform checking outside of TootSDK (my fork has TootSDKFlavour/Feature removed and I don't do the connect call) but definitely it would be handier to have nodeinfo at the tootsdk level, so I can reference it from my session layer.

**Comment by technicat** [comment]
btw, Feditext is the only other app I know that checks nodeinfo (it's open source, so you can take a look at their implementation)

**Comment by Tunous** [comment]
Good to see a confirmation that nodeinfo is a way to go. I added detection via it in #288.

**Comment by technicat** [comment]
I've found fedidb.org is really useful for researching this stuff, it displays the nodeinfo for every site listed and if available the v1 instance.
