### ISSUE TITLE
Broken pleroma pagination

### ISSUE THREAD

**Issue by Tunous** [TootSDK/TootSDK#326]
Given a request for home timeline with `min_id` Pleroma responds with different pagination links than Mastodon. Mastodon responds with `max_id` in link for next page and `min_id` in link for previous page. Pleroma instead includes both `max_id` and `min_id` for both links. This breaks because TootSDK extracts first encountered query value, no matter in which link it was received.

I'm raising this as a issue instead of pull request because I'm not entirely sure how proper fix should work. Should min_id be extracted only from prev link, or maybe both should be returned for user to decide? Or maybe something entirely different?

Ultimately what I want to have is:
When I request a timeline, in response I want to receive posts and information what to send to receive previous or next page.

**Comment by Tunous** [comment]
Possibly related to #311.

**Comment by kkostov** [comment]
The library supports receiving all 3 parameters simultaneously in the Link header of the response (cf. `Pagination(links)`). This populates each of the 3 fields but I think `PagedResult` may incorrectly evaluate `hasNext` if both `max_id` and `min_id` are provided. In this case, `hasNext` will report `true` even if there aren't really more results in the "next" direction.

Is the issue you've detected? Do you have an example header header value which triggered the problem?

If the solution is too complex as a bugfix or requires knowledge of the connected flavour, I suggest that we proceed with a flavour specific interface e.g. splitting `Pagination` and/or `PagedResult` into a general and pleroma flavoured implementation with a common interface. This is based [on (3)](https://github.com/TootSDK/TootSDK/pull/321#issue-2606648966) from #321 (e.g. `PleromaLinkParser` if the issue is in parsing, or `PleromaPagedLinkBuilder` to provide the `hasPrevious`, `hasNext`, `nextPage` and `previousPage` - naming can be tweaked of course).

Regarding #311, I don't think it's related as that's just a discussion about the naming of the cursor API (what's "previous" and whats "next").

**Comment by Tunous** [comment]
Almost, but a bit different. Here is an example:

```
<https://aaa/api/v1/timelines/public?limit=40&local=true&max_id=AAA&min_id=BBB&offset=0&only_events=false&only_media=false&remote=false&local=true>; rel="next", <https://aaa/api/v1/timelines/public?limit=40&local=true&min_id=AAA&offset=0&only_events=false&only_media=false&remote=false&local=true>; rel="prev"
```

Notice how "next" has both max_id and min_id. Because of that I'm unable to access min_id from "prev". I'll always get BBB which is incorrect if I want previous page.

**Comment by kkostov** [comment]
Indeed, it seems our current approach is not sufficient to support this.
My suggestion would be to adapt `PagedInfo` so it retains all 3 parameters for `prev` and `next`) e.g. `{"prev": {min_id: .., max_id: ..., since_id: ...}, "next": {min_id: .., max_id: ..., since_id: ...}}` and this will be used when the corresponding link is requested.
