### ISSUE TITLE
Renderer tests are not able to build using Foundation on Linux

### ISSUE THREAD

**Issue by kkostov** [TootSDK/TootSDK#60]

**Comment by technicat** [comment]
Btw, in my tootsdk fork I moved the renderer to the swiftui toot demo (I guess it needs to be in the vapor demo too, but I'm just freely breaking things), on the theory that tootsdk should be renderer independent, and I'm actually using the HTML2Markdown package from @divadretlaw (actually a fork with custom rendering) which you might consider using instead since you're also using his EmojiText package, and it's more exhaustive, e.g. paragraph breaks come out better.
